spring.application.name=Backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=86400000
spring.ecom.app.jwtCookieName=ECommJwtToken

logging.level.com.ayansh.E_Comm.Controller=DEBUG
logging.level.com.ayansh.E_Comm.Service=DEBUG
spring.jackson.deserialization.fail-on-null-for-primitives=true
logging.level.org.springframework.web.reactive.function.client=DEBUG

agro.api.key=${AGRO_API_KEY}
agro.api.url=https://api.agromonitoring.com
openweather.api.key=${OPENWEATHER_API_KEY}
openweather.api.url=https://api.openweathermap.org

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}

server.port=${PORT:8080}

